# See: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
version: 2.1

jobs:
  docs-build:
    docker:
      - image: circleci/python:3.8.1-buster
    environment:
      CODECOV_TOKEN: "24ebd27b-4413-4e7e-acbd-46499658bd1e"
    steps:
      - checkout

      # make sure pandoc is on the system
      - run: sudo apt-get update && sudo apt-get install -y pandoc

      # restore cache from last build. Unless __init__.py has changed since then
      - restore_cache:
          keys:
            - data-cache-0-{{ checksum "./morf/__init__.py" }}

      # Also restore pip cache to speed up installations
      - restore_cache: # ensure this step occurs *before* installing dependencies
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Setup Python environment via Pipenv
          command: |
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install --skip-lock --dev

      - run:
          name: Run unit and integration tests
          command: |
            pipenv run make pep
            pipenv run pytest --cov=morf ./tests/ --cov-report=xml --cov-config=setup.cfg --verbose

      - store_artifacts:
          path: ./coverage.xml

      - run:
          name: Upload codecov report
          command: |
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build the documentation
          command: |
            pipenv run make build-doc

      - persist_to_workspace:
          root: docs/_build
          paths: html

      - store_artifacts:
          path: docs/_build/html/
          destination: dev
#      - run:
#          name: Check links
#          command: |
#            pipenv run make -C doc clean
#            pipenv run make -C docs linkcheck
#            pipenv run make -C doc linkcheck-grep

      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/venv"

workflows:
  commit:
    jobs:
      - docs-build